# Generated by Django 2.2.5 on 2019-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0004_auto_20190923_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='settled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
