# Generated by Django 2.2.5 on 2019-10-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_api', '0006_mpesapayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='drugs',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='visitor_count',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
